// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "../globals.css";

// import { NextIntlClientProvider } from "next-intl";
// import { getLocale, getMessages } from "next-intl/server";

// import Providers from "@/ReactQueryProvider";
// import { ThemeProvider } from "../Context/ThemeContext";

// import Sidebar from "./_components/Sidebar/Sidebar";
// import Navbar from "./_components/Navbar/Navbar";

// // Font configuration
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// // Metadata
// export const metadata: Metadata = {
//   icons: {
//     icon: "/images/logotsline.png",
//   },
//   title: "SmartArkSys",
//   description: "Generated by create next app",
// };

// // Layout
// export default async function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   const messages = await getMessages();
//   const locale = await getLocale();

//   return (
//     <html lang={locale}>
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <ThemeProvider>
//           <NextIntlClientProvider messages={messages}>
//             <Providers>
//               <div className="flex flex-col min-h-screen">
//                 <Navbar />

//                 <div className="flex flex-1">
//                   <Sidebar />

//                   <main className="flex-1 p-6 bg-white dark:bg-gray-dark">
//                     {children}
//                   </main>
//                 </div>
//               </div>
//             </Providers>
//           </NextIntlClientProvider>
//         </ThemeProvider>
//       </body>
//     </html>
//   );
// }
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Providers from "../ReactQueryProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  // title: "Create Next App",
  title: "SMARTARK SYS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
