import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "../../globals.css";

import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";

// import Providers from "@/ReactQueryProvider";

import Sidebar from "./_components/Sidebar/Sidebar";
import Navbar from "./_components/Navbar/Navbar";
// import { ThemeProvider } from "@/components/Context/ThemeContext";
import Providers from "@/app/ReactQueryProvider";
import { ThemeProvider } from "@/app/Context/ThemeContext";

// Font configuration
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// Metadata
export const metadata: Metadata = {
  icons: {
    icon: "/images/logotsline.png",
  },
  title: "SMARTARK SYS",
  description: "Generated by create next app",
};

// Layout
// export default async function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   const messages = await getMessages();
//   const locale = await getLocale();

//   return (
//     <html lang={locale}>
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <ThemeProvider>
//           <NextIntlClientProvider messages={messages}>
//             <Providers>
//               <div className="flex flex-col min-h-screen">
//                 {/* Navbar at the top */}
//                 <Navbar />

//                 {/* Main area with sidebar and content */}
//                 <div className="flex flex-1">
//                   {/* Sidebar on the left */}
//                   <Sidebar />

//                   {/* Page content */}
//                   <main className="flex-1 p-6 bg-white dark:bg-gray-dark">
//                     {children}
//                   </main>
//                 </div>

//                 {/* Footer at the bottom */}
//               </div>
//             </Providers>
//           </NextIntlClientProvider>
//         </ThemeProvider>
//       </body>
//     </html>
//   );
// }
export default async function AdminSupportLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const messages = await getMessages();

  return (
    <ThemeProvider>
      <NextIntlClientProvider messages={messages}>
        <Providers>
          <div className="flex flex-col min-h-screen dark:bg-gray-dark">
            <Navbar />
            <div className="flex flex-1">
              <Sidebar />
              {/* <main className="flex-1 p-6 bg-white dark:bg-gray-dark"> */}
              <main className="ml-[250px] flex-1 p-6 bg-white dark:bg-gray-dark mt-15">
                {children}
              </main>
            </div>
          </div>
        </Providers>
      </NextIntlClientProvider>
    </ThemeProvider>
  );
}
